@startuml proposeOffer
title **Propose Offer**
skinparam sequenceMessageAlign center
skinparam maxMessageSize 130
actor Bob
box "Website" #LightBlue
entity UI
control ZokratesLibrary
end box
database Blockchain

Bob -> UI: Puts his password to prove that he's the garden's owner
note left: Bob wants to propose an offer

UI -> ZokratesLibrary: Sends Bob's password locally in browser
ZokratesLibrary->ZokratesLibrary: Computes password's hash and creates proof of knowledge of preimage
ZokratesLibrary->UI: Sends Bob's proof locally
UI -> Blockchain: Sends Bob's proof within the offer
Blockchain->Blockchain: Verifies proof and create offer if succeed

@enduml