@startuml getBackGardenAccessCode
title **Get Back Garden Access Code**
skinparam sequenceMessageAlign center
skinparam maxMessageSize 130
actor Alice
box "Website" #LightBlue
entity UI
control EthCryptoLibrary
end box
database Blockchain

Alice -> UI: Requests the encrypted garden access code for her location
UI -> Blockchain: Requests encrypted garden access code
Blockchain -> UI: Sends back encrypted garden access code if Alice is the correct tenant
UI -> Alice: Sends back garden code

Alice -> EthCryptoLibrary: Sends encrypted code and her Ethereum private key
EthCryptoLibrary -> EthCryptoLibrary: Decrypts garden access code
EthCryptoLibrary -> Alice: Sends back plain garden access code

@enduml