@startuml acceptOffer
skinparam sequenceMessageAlign center
skinparam maxMessageSize 130
actor Alice
entity Website
database Blockchain

Alice -> Website: Send correct amount of ether and sign "sign me"
Website -> Blockchain: Offer is accepted if ethers sent > required amount and signature is saved

@enduml