@startuml interactions
skinparam sequenceMessageAlign center
skinparam maxMessageSize 130
actor Bob
entity Website
control Zokrates
database Blockchain

Bob -> Website: Put his password to prove that he's the garden's owner
note left: Bob wants to propose an offer

Website -> Zokrates: Send Bob's password locally in browser
Zokrates->Zokrates: Compute password's hash and creates proof of knowledge of preimage
Zokrates->Website: Send Bob's proof locally
Website -> Blockchain: Send Bob's proof within the offer
Blockchain->Blockchain: Verify proof and create offer if succeed

@enduml