@startuml send garden access code 
skinparam sequenceMessageAlign center
skinparam maxMessageSize 130

actor Bob
box "Website" #LightBlue
entity UI
control EthCryptoLibrary
end box

database Blockchain

Bob -> UI: Send garden access code for a specific garden
UI-> UI : Hash garden access code
UI -> Blockchain: Request tenant signature for the requested garden
Blockchain-> UI : Send back tenant's signature of "sign me"
UI-> EthCryptoLibrary: Send garden access Code and tenant signature
EthCryptoLibrary -> EthCryptoLibrary: Extracts the tenant's public key and encrypts the garden access code
EthCryptoLibrary -> UI : Send back encrypted garden access code
UI -> Blockchain : Send encrypted garden access code and hashed access code to blockchain

@enduml